var EVENT = {
    PLAYER: {
        GAME_START: 'GAME_START',
        PLAYBACK_OVER: 'PLAYBACK_OVER'
    },
    PLAYBACK: {
        GAME_START: 'GAME_START',
        PLAYER_OVER: 'PLAYER_OVER'
    },
    MEDIATOR: {
        PLAYER_READY: 'PLAYER_READY',
        PLAYER_START: 'PLAYER_START',
        PLAYER_OVER: 'PLAYER_OVER',
        PLAYBACK_READY: 'PLAYBACK_READY',
        PLAYBACK_OVER: 'PLAYBACK_OVER'
    }
    
};